services:
  db-dev:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: jaa_dev_user
      POSTGRES_PASSWORD: jaa_dev_password
      POSTGRES_DB: jaa_dev_db
    ports: 
      - "5432:5432"
    volumes: 
      - "jaa_dev_data:/var/lib/postgresql/data"
    
  db-prod:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: jaa_prod_user
      POSTGRES_PASSWORD: jaa_prod_password
      POSTGRES_DB: jaa_prod_db
    ports: 
      - "5433:5432"
    volumes: 
      - "jaa_prod_data:/var/lib/postgresql/data"

volumes:
  jaa_dev_data:
  jaa_prod_data: